name: mnist-train-component
description: Train CNN with MNIST data
inputs:
  - {name: input_data_folder_path, type: LocalPath, description: 'Input folder path'}
  - {name: output_model_folder_path, type: LocalPath, description: 'Output folder path'}
outputs:
  - {name: output_model_folder_path, type: LocalPath, description: 'Output folder path'}
implementation:
  container:
    image: guobowen1990/mnist
    command: [python, /work_dir/src/train.py]
    args: [
      --input-data-folder-path, {inputValue: input_data_folder_path},
      --output-model-folder-path, {outputPath: output_model_folder_path}
    ]