name: MNIST - Train CNN
description: Train CNN with MNIST data
inputs:
  - {name: MNIST data, type: LocalPath, description: 'MNIST data'}
  - {name: Number of steps, type: Integer, description: 'Number of steps to train CNN'}
outputs:
  - {name: Trained model, type: LocalPath, description: 'Trained model'}
implementation:
  container:
    image: guobowen1990/mnist-pipeline:0.0.2
    command: [python, /work_dir/src/train.py]
    args: [
      --input-data-folder-path, {inputValue: MNIST data},
      --number-of-steps, {inputValue: Number of steps}
      --output-model-folder-path, {outputPath: Trained model}
    ]